author: Multitallented
database: false
description: Puts players in a queue for pvp games against other players of the same skill level
main: org.redcastlemedia.multitallented.instantarenas.InstantArenas
name: InstantArenas
load: POSTWORLD
version: 1.0-SNAPSHOT
api-version: 1.14
commands:
  ia:
    aliases: ['instantarenas']
    description: InstantArenas commands
    usage: /<command>
permissions:
  heromatchmaking.queue:
    description: Lets you use /ia queue
    default: true
